# Generated by Django 5.1.6 on 2026-04-05 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('earned', 'Earned/Vacation Leave'), ('unpaid', 'Unpaid Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('comp_off', 'Compensatory Off')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'db_table': 'leaves',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='leaves_employe_da7fd0_idx'), models.Index(fields=['status', 'start_date'], name='leaves_status_41bf53_idx'), models.Index(fields=['-created_at'], name='leaves_created_d32228_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('earned', 'Earned/Vacation Leave'), ('unpaid', 'Unpaid Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('comp_off', 'Compensatory Off')], max_length=20)),
                ('year', models.IntegerField()),
                ('total_days', models.IntegerField(default=0, help_text='Total allocated days')),
                ('used_days', models.IntegerField(default=0, help_text='Days used this year')),
                ('balance_days', models.IntegerField(default=0, help_text='Remaining balance days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balances',
                'ordering': ['employee', 'leave_type', 'year'],
                'indexes': [models.Index(fields=['employee', 'year'], name='leave_balan_employe_ee6624_idx'), models.Index(fields=['leave_type', 'year'], name='leave_balan_leave_t_d570cf_idx')],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
