# Generated by Django 5.1.6 on 2026-04-05 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('notification_type', models.CharField(choices=[('leave_applied', 'Leave Applied'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('checkin', 'Check-in'), ('checkout', 'Check-out'), ('user_created', 'User Created'), ('role_assigned', 'Role Assigned'), ('mention', 'Mention'), ('system', 'System'), ('info', 'Information')], default='info', help_text='Type of notification', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when notification is clicked', max_length=500)),
                ('action_text', models.CharField(blank=True, help_text='Text for the action button', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata associated with the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was marked as read', null=True)),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx')],
            },
        ),
    ]
